FROM ubuntu:22.04

# ENV DEBIAN_FRONTEND=noninteractive

# # Install necessary packages
# RUN apt update --yes
# RUN apt install --yes curl unzip tar 
# RUN apt-get --quiet install --yes software-properties-common
# RUN apt-get install git --yes

# # Node Install
# RUN curl -sL https://deb.nodesource.com/setup_14.x -o /tmp/nodesource_setup.sh
# RUN bash /tmp/nodesource_setup.sh
# RUN apt install nodejs
# RUN node -v

# Install App
RUN cd C:/tera-aws/tech-git/devops-fullstack-app

